version: '2'

services:
  netdata:
    image: titpetric/netdata
    container_name: netdata
    cap_add:
      - SYS_PTRACE
    ports:
      - "19999:19999"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
